### ISSUE TITLE
request from a noob that loves your work

### ISSUE THREAD

**Issue by BlankeTea** [Darkhax-Minecraft/Coins#11]
**Sorry i never used github before** , i simply would live to know if you will ever consider making a version for 1.12.2 
**I really love your mod** and would love to use it.
Im sorry if this an unwanted request! i just thought id not lose anything if i try..
**Great work  by the way im very thankful for the free quality mod that u are sharing with the community** even if you decide not to make it available for 1.12.2  !

**Comment by Darkhax** [comment]
Hello, no there are no plans to back port this to older versions at this time.
