### ISSUE TITLE
[Request] Add a netherite coin tier?

### ISSUE THREAD

**Issue by ConqAra** [Darkhax-Minecraft/Coins#12]
Not really a reason but it would be satisfying to have that next tier as an option.

**Comment by Darkhax** [comment]
Hello, this is being considered for 1.17. The change would look something like this

Copper -> Iron -> Gold -> Platinum -> Diamond

becomes

Copper -> Iron -> Gold -> Diamond -> Netherite

Existing platinum coins would become Diamond, and existing Diamond coins would become Netherite. How copper ingots, diamonds, and Netherite scrap can be converted into coins is still being considered.

**Comment by ConqAra** [comment]
yeah, that's a lot better, considering platinum is no where to be seen in the vanilla game. And since copper will be added to the game in 1.17, it'll be perfect. This would give a lot more of a vanilla feel. I like it!

**Comment by LeftDark7** [comment]
hello I want to ask if this mod will be able to be optimized for 1.12.2 because many people play old mod not new

**Comment by Guinaro** [comment]
Can we then also added an Emerald Coin?
Copper -> Iron -> Gold -> Diamond -> Emerald -> Netherite
On 1.16.5 you could drop the Copper and still have all elements represented by vanilla items.

**Comment by Darkhax** [comment]
The new tier order as of 1.18.2 is 

> Copper -> Iron -> Gold -> Diamond -> Netherite

Converting between tiers works the same as the previous version. 

Copper Ingots can now be created by smelting copper ingots, similarly to how Iron coins and Gold coins can be created.
