### ISSUE TITLE
alternative coin upgrades: base 10

### ISSUE THREAD

**Issue by Ikxale** [Darkhax-Minecraft/Coins#14]
a good alternative to coin upgrades could be to combine a stack and a coin together, which would allow for the coins to be base 10, and then to downgrade coins just have one higher coin turn into ten lower coins

also, it would make it much easier to set up auto crafting of coins and reduce the need for large amounts of coal or charcoal to exchange

**Comment by Darkhax** [comment]
Adding an additional crafting step doesn't sound very friendly for auto crafting, and would make the recipes less auto-craftable in vanilla. The furnace fuel cost is also an intentional design choice as it introduces a "fee" to conversions.
