### ISSUE TITLE
[Request] Change Villager currency to coins

### ISSUE THREAD

**Issue by Khaeops** [Darkhax-Minecraft/Coins#19]
I'd love to be able to use these coins in villager trades instead of emeralds. A config for scaling would be great too, so we can define a range of how much 1 emerald vs. 64 emeralds is worth in coins.

**Comment by Darkhax** [comment]
Hello, thanks for the suggestion. This would be a nice feature however there is no straight forward way to replace all villager trades with coins, especially when factoring in trades added by mods. For that reason this is out of scope for this mod.
