### ISSUE TITLE
[Cheeky Request] please back-port for 1.14

### ISSUE THREAD

**Issue by Royal-Jelly** [Darkhax-Minecraft/Coins#2]
I'm almost certain requests like this are frowned at, but i have to ask since it seems like 1.14.4 is where all the mods will be staying for "lts" support from the forge development team

**Comment by puggan** [comment]
Took a look at it, and its depends on function in Bookshelf, that's wasn't avaible in 1.14.4-4.4.74,
so that package need some back-porting first. So put an Issue in that repo, and may try to backport it next week-

**Comment by Royal-Jelly** [comment]
Thanks puggan for the reply, I will move discussion to the appropriate place

**Comment by puggan** [comment]
@Darkhax According to your comment in Bookshelf, it's sound like you suggesting removing the loot-table-injection in a backport of Coins.

@Royal-Jelly if that is an acceptable lose, [ie](https://en.wikipedia.org/wiki/List_of_Latin_phrases_(I)#id_est) the coins can't be found in village chests, then I think I can make an 1.14.4 version, and make a pull request for it.

https://github.com/Darkhax-Minecraft/Coins/blob/eade28632979d74e190325e284a9c7e058833490/src/main/java/net/darkhax/coins/Coins.java#L37-L54

**Comment by puggan** [comment]
@Darkhax Don't know how to make a PR to a new branch, didn't wanted to make a PR for the 1.15.2 branch.

Here is a downgraded version:
https://github.com/puggan/Coins/tree/1.14.4/no-chest-loot

Tested all recipts, and the creative-mode-tab. Works fine in 1.14.4, but the loot-injectin is out-commented.

**Comment by Royal-Jelly** [comment]
thank you very much for this puggan, and sorry about the late reply life came up

**Comment by Darkhax** [comment]
Sorry for missing this. Life has been crazy lately. Thanks for the PR, it's now been merged and is on CF.
