### ISSUE TITLE
Feature request: Add extra coins, but not linked to the chain of value from copper up to netherrite

### ISSUE THREAD

**Issue by Lothrazar** [Darkhax-Minecraft/Coins#29]
I love this mod and the coins and recipes all look amazing.

My feature request is to add the following: new coins and coin piles for 
- Emerald Coin (from smelting emerald block)
- Lapis Coin (smelt lapis block)
- Redstone Coin (smelt redstone block)
- Amethyst Coin (Smelt amethyst block)
and a coin pile for each so 8 items
However these would not be linked in any way to other coin types. like in the way a copper pile can become one iron coin, and one diamond pile smelts into one netherite coin, these Lapis Coin, Redstone Coin, and Emerald Coin can only stay as themselves.

Why add these?
-Other mods can add custom villager trades, custom recipes based on these coins, or their own trading systems.
-Mods and modpacks can use these as special quest rewards or special sets of currency.  Like in mobile games how theres the trash currency and then the medium stuff and then the Real good stuff premium currency. 
- mods can integrate these coins into their crafting and trading systems knowing some coins can be 'converted' (smelting piles)and some cannot
-Adds flavor, they would look great with this texture style in those colours.
(could maybe have ender/blaze coin but that gets into mob drops, probably too much)

If you feel these dont fit in the mod theme, maybe you could make new secind addon mod? that depends on this one and ppl can download both or just one mod.  
(Only in mc 1.20.1+ is enough of course)
Thanks for considering

**Comment by Darkhax** [comment]
Thanks for the feature request. I've considered adding this before but I didn't think anyone would use them but I guess your request shows otherwise. It may take a bit but I will add this to my TODO list.

**Comment by Darkhax** [comment]
I finally had some time to look at this. I've added a bunch of new coins in 16.0.3 for MC 1.20.4. The textures aren't all hits, but a few of them look pretty cool. Right now they are all unobtainable in survival but there recipes for coins to piles and piles back to coins. It's easy enough for modpacks and servers to implement the rest. Thanks again for the suggestion.
