### ISSUE TITLE
1.15.2 Naturally spawning chests dont have loot inside

### ISSUE THREAD

**Issue by Blugori** [Darkhax-Minecraft/Coins#3]
SO I have no idea why but when this mod is installed vanilla chests in structures like villages doesnt have any items inside ! I didnt test with only the mod coins installed, but it only happens when coins is installed.
Im using forge 31.2.0

**Comment by Darkhax** [comment]
Are there any errors in your log/console?

**Comment by Darkhax** [comment]
This feature is now removed anyhow.
