### ISSUE TITLE
Mod conflict with moving elevators

### ISSUE THREAD

**Issue by Spicykurenai** [Darkhax-Minecraft/Coins#30]
[](https://github.com/SuperMartijn642/MovingElevators/issues/174 )

Minecraft 1.20.1 tested both forge 47.1.3 and 47.1.33

Tested both client and multiplayer. 

The issue is the banner images do not appear at all when using the loom or after it is crafted. 

Mods included are in the image: 

![mods](https://github.com/Darkhax-Minecraft/Coins/assets/140019749/24b915c7-1afd-4d0a-9f69-7aaa562b7478)

**Comment by Darkhax** [comment]
Closing this now as I believe we solved the issue on Discord. 

> SuperMartijn642 said he fixed it in his core library 1.1.11 and appreciated the issue report.
