### ISSUE TITLE
Noaaan's Mythic Metals Compat

### ISSUE THREAD

**Issue by eclipseddaemond** [Darkhax-Minecraft/Coins#31]
It would be so extremely awesome if support for metals from [Noaaan's Mythic Metals](https://modrinth.com/mod/mythicmetals) was also added. This is a universal mod for extra metals. 
There is no great need to attach them to the main coin chain. The ability to melt nuggets into coins would be sufficient. (Or perhaps it would be useful to have an alternative (possibly configurable) chain for non-vanilla metals.

**Comment by Darkhax** [comment]
Thanks for this suggestion. I looked into Mythic Metals earlier today. While I would love to offer every possible coin everyone could ever want, making the pallets and textures actually takes a fair bit of time. It's really hard to justify spending so much time on support for a single mod. Especially when a lot of the materials are not commonly used across other mods and only fit within this specific niche. 

If someone wants to make their own add-on to add the dozens of metals from Mythic Metals they're more than welcome to.
