### ISSUE TITLE
Create mod metals compat

### ISSUE THREAD

**Issue by eclipseddaemond** [Darkhax-Minecraft/Coins#32]
It would be really cool to add zinc and brass coins. With the possibility of upgrading 1 Copper and 1 Zinc into 1 Brass coin (but not back (or even back to 1 Copper and 1 Zinc coins).

**Comment by Darkhax** [comment]
Thanks for the suggestion, I finally had time to look into this today and added these coins in 16.0.3 for MC 1.20.4. Right now the coins are not obtainable in survival. I don't want to integrate these into the main exchange tree though and figured it would be best to let modpacks and servers decide how players get/use them themselves. The only included recipes are coins -> piles and piles -> coins.
