### ISSUE TITLE
Backport to 1.12.2?

### ISSUE THREAD

**Issue by vizthex123** [Darkhax-Minecraft/Coins#4]
Title. This is perfect for what I'd like but sadly isn't updated.

**Comment by Darkhax** [comment]
Hello, given everything that's going on right now I do not have time to make this backport. If a community member wants to help backport it I will accept a PR.

**Comment by puggan** [comment]
I can take a look at it, but currently doing PR:s for 1.16.1 on all mods in my modpack.
